### ISSUE TITLE
Plugin compilation fails

### ISSUE THREAD

**Issue by futuresplash** [raph-amiard/sublime-typescript#1]
I get the following message when compiling the plugin:

```
The property 'stdin' does not exist on value of type 'process'
make: [bin/main.js] Error 1 (ignored)
```

I have the latest node version.
Assuming the error was ignored, I load Sublime and get syntax coloring, but autocompletion does not work.
I get the following message on the status bar:

```
Loading typescript plugin /
```

with a spinning dash, And it keeps doing that forever.

**Comment by raph-amiard** [comment]
Hey, thank you for the report, the error is expected, that's why it is ignored.

Could you open the python console in sublime script and post me the log ?

**Comment by futuresplash** [comment]
Sure.
Here goes what I believe is the relevant part of the log, written during the application startup:

```
IN ON LOAD FOR VIEW :  /Users/claudio/Library/Application Support/Sublime Text 2/Packages/sublime-typescript/src/ts/main.ts
PLUGIN_FILE  /Users/claudio/Library/Application Support/Sublime Text 2/Packages/sublime-typescript/bin/main.js
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 477, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./typescript.py", line 108, in init_async
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1106, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

I also get errors when pressing Ctrl + Space for autocompletion.

I'm using Sublime Text 2.01, build 2217, on OS X Mountain Lion.

**Comment by raph-amiard** [comment]
Ok it means the plugin can't find the script to execute it, there must be a path problem. I'm gonna push a commit with some more debugging ASAP, i'll keep you posted !

**Comment by raph-amiard** [comment]
Hey, i pushed a log commit that should output new information to the console, can you give me the line that begins by "PLUGIN_PATH" please ?

**Comment by futuresplash** [comment]
Thanks for looking into this. I'm really looking forward to being able to use typescript autocompletion on Sublime! :-)

I've updated the plugin like this:

```
make clean
git pull
make
```

And now I have the following messages in the log, on startup:

```
IN ON LOAD FOR VIEW :  /Users/claudio/Library/Application Support/Sublime Text 2/Packages/sublime-typescript/src/ts/main.ts
PLUGIN_FILE  PLUGIN PATH :  /Users/claudio/Library/Application Support/Sublime Text 2/Packages/sublime-typescript
/Users/claudio/Library/Application Support/Sublime Text 2/Packages/sublime-typescript/bin/main.js
PLUGIN PATH :  /Users/claudio/Library/Application Support/Sublime Text 2/Packages/sublime-typescript
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 477, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./typescript.py", line 109, in init_async
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 595, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/subprocess.py", line 1106, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

The "IN ON LOAD FOR VIEW" path exists.
The "PLUGIN_FILE  PLUGIN PATH" path exists (both sublime-typescript and main.js).
The "PLUGIN PATH" path exists.

**Comment by raph-amiard** [comment]
Well, i think the problem is that python can't find your node executable. Node presently needs to be on your path when you execute typescript. I'm gonna update the script with better error reporting.

**Comment by futuresplash** [comment]
Node is in my path at /usr/local/bin/node
I can access it fine via the bash command line.
I remember reading in a forum a while ago that given there are many ways to define the path on OSX, some programs may not get the same PATH as others. I remember the problem was that IDEA IDE was not able to find Node for an external build tool.
I do not rember the solution, though.
Is there some way to know the PATH Sublime is receiving?
Is there some way to define the Node path for this plugin?  Via config file or environment variable, perhaps?

**Comment by raph-amiard** [comment]
Hey, i'm gonna add a way to set the node path via a config file, i'll keep
you posted about that

2013/1/25 futuresplash notifications@github.com

> Node is in my path at /usr/local/bin/node
> I can access it fine via the bash command line.
> I remember reading in a forum a while ago that given there are many ways
> to define the path on OSX, some programs may not get the same PATH as
> others. I remember the problem was that IDEA IDE was not able to find Node
> for an external build tool.
> I do not rember the solution, though.
> Is there some way to know the PATH Sublime is receiving?
> Is there some way to define the Node path for this plugin? Via config file
> or environment variable, perhaps?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/raph-amiard/sublime-typescript/issues/1#issuecomment-12705259.

## 

Raphaël AMIARD

**Comment by raph-amiard** [comment]
Ok i've added an option to set the node path via a "node_path" key in your settings, checkout the README for more details and tell me if it works :)

**Comment by SPY** [comment]
i have same error after last update, and i add path to node to node_path

``` javascript
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 522, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 477, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./typescript.py", line 116, in init_async
  File "./typescript.py", line 98, in get_node_path
RuntimeError: Must call on main thread, consider using sublime.set_timeout(function, timeout)
```

and i got that error too

``` javascript
The property 'stdin' does not exist on value of type 'process'
make: [bin/main.js] Error 1 (ignored)
```

**Comment by raph-amiard** [comment]
Hey, thank you for the report, the make error is expected, i'll find a way around it because it seems to be confusing !

The thread error is actually a different one, i'll fix it and keep you updated

**Comment by futuresplash** [comment]
Besides the error SPY reported above, I also get the following error when pressing Ctrl+Space on a TypeScript file:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 236, in on_query_completions
  File "./typescript.py", line 378, in on_query_completions
  File "./typescript.py", line 143, in serv_get_completions
  File "./typescript.py", line 129, in msg
AttributeError: 'PluginInstance' object has no attribute 'p'
Exception in thread Thread-14:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./typescript.py", line 338, in work
  File "./typescript.py", line 147, in serv_get_errors
  File "./typescript.py", line 129, in msg
AttributeError: 'PluginInstance' object has no attribute 'p'
```

**Comment by raph-amiard** [comment]
Hey futuresplash, the error you get is due to the previous exception. It should be fixed now (hopefully).

Theses threads errors are extremely annoying because they arise from a restriction in the Mac version of sublime text (you can't call API functions from threads) that the linux version doesn't have (yet i think). So i get no error on linux whatsoever.

**Comment by futuresplash** [comment]
Thanks!
I no longer have errors on startup.

Unfortunately, the plugin not always works.
I created a new issue for it, as this issue is about the problems during the plugin startup, which seem to be fixed now.
