### ISSUE TITLE
Plugin won't load

### ISSUE THREAD

**Issue by nathanboktae** [raph-amiard/sublime-typescript#10]
OS X 10.8.2, tried with typescript repo and downloaded sources in another issue, no luck

```
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(*self.__args, **self.__kwargs)
  File "./typescript.py", line 188, in init_async
  File "./typescript.py", line 206, in serv_add_file
  File "./typescript.py", line 202, in msg
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init__.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

**Comment by mode80** [comment]
I was able to fix this by manually copying the typescript source code into the plugin's lib/typescript directory, then running 'make' at the plugin's root directory before opening ST2.

**Comment by raph-amiard** [comment]
Hi, i need more information on this. 

Normally, with this here version everything is automated. 
But with the old version of the plugin, you needed to clone the repo with --recursive to get submodules. 

Try to re-install the plugin now and tell me if it works as planned on mac. I can't test on mac so any help would be appreciated.

**Comment by mattpolzin** [comment]
I am on a mac and after cloning the repo (without --recursive) and opening a typescript file, I get a very similar stack trace:

IN ON LOAD FOR VIEW :  /Users/matt/staging/Vadio/vadio/static/js/core/PlaylistItem.ts
PLUGIN_FILE  /Users/matt/Library/Application Support/Sublime Text 2/Packages/Typescript/bin/main.js
OUT OF INIT ASYNC
Exception in thread Thread-8:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "./typescript.py", line 247, in init_view_async
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file

 ... (many, many more lines of the same here)

  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 233, in init_file
  File "./typescript.py", line 209, in serv_add_file
  File "./typescript.py", line 205, in msg
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/**init**.py", line 307, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by damassi** [comment]
I'm getting the same issue.  The plugin hangs, stating "Loading typescript plugin".  I've had it running for an hour or so, with no output being reflected in the directory.  

Perhaps you could write out more thorough, step-by-step install instructions?  The comment about --recursive, copying sources (where?) etc is all quite vague.

**Comment by raph-amiard** [comment]
Hi, i'm sorry, the README wasn't up to date, i updated it.

The truth is you don't need to do anything except clone the plugin in your packages folder.

Are you on a Mac too ? It's working fine on Linux and Windows as far as i know, and i don't have an access to an Apple computer right now to see what the problem is.

**Comment by damassi** [comment]
Thanks for the update.  I realized that it was a permissions issue on the folder.  Since it's fetching, it needs complete access -- read / write.

**Comment by nathanboktae** [comment]
I was able to get this working for ST2 with the latest revision, and explicitly setting my node path - thanks. Closing.

**Comment by karimbeyrouti** [comment]
Same issue, OsX, Sublime 2. How did you guys resolve it ? 

OUT OF INIT ASYNC
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 532, in **bootstrap_inner
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/threading.py", line 484, in run
  File "./typescript.py", line 247, in init_view_async
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 238, in init_file
  File "./typescript.py", line 233, in init_file
  File "./typescript.py", line 209, in serv_add_file
  File "./typescript.py", line 205, in msg
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/__init**.py", line 307, in loads
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 319, in decode
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/json/decoder.py", line 338, in raw_decode
ValueError: No JSON object could be decoded

IN ON LOAD FOR VIEW :  /Users/karimbeyrouti/Library/Application Support/Sublime Text 2/Packages/sublime-typescript/lib/typescript/README.txt

**Comment by nabils** [comment]
Me too getting the same error. Its a shame would really like to use this. I am behind a proxy so have to install manually. I followed the offline install instructions by cloning https://github.com/raph-amiard/sublime-typescript into the ST2 packages folder and then cloning the typescript source at https://git01.codeplex.com/typescript into the package lib directory.
