### ISSUE TITLE
Autocompletion frequently fails

### ISSUE THREAD

**Issue by futuresplash** [raph-amiard/sublime-typescript#2]
This issue is really two issues in one.
#### Dot completion

Sometimes I get this error when invoking autocompletion after a dot:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 236, in on_query_completions
  File "./typescript.py", line 381, in on_query_completions
  File "./typescript.py", line 77, in completions_ts_to_sublime
  File "./typescript.py", line 53, in format_completion_entry
KeyError: u'keyword'
```

Then I just get the standard Sublime autocompletion dropdown with dummy suggestions.
#### Middle-of-word completion

Additionaly, if I press Ctrl+Space with the cursor on the second char of the word following a dot (ex: on the 'e' of `this.test`), I get the error:

```
Traceback (most recent call last):
  File "./sublime_plugin.py", line 236, in on_query_completions
  File "./typescript.py", line 381, in on_query_completions
  File "./typescript.py", line 77, in completions_ts_to_sublime
  File "./typescript.py", line 53, in format_completion_entry
KeyError: u'constructor'
```

This is similar to the other error above, but now it mentions 'constructor' instead of 'keyword'.

What I was expecting would be a list of completions filtered by the first letter (on the example above, only completions starting with 't' would be shown).

**Comment by raph-amiard** [comment]
Hey futuresplash !

The key-errors should be quite easy to fix. It would help though if you could isolate a code sample with this behaviour so i can be sure i fixed it.

Middle of word member completion is not implemented yet, i'll add it ASAP

**Comment by raph-amiard** [comment]
The issue should be fixed now. Tell me if it works ok for you.

**Comment by futuresplash** [comment]
It works just fine!!
The errors are gone and middle-of-word completion is working too.
Awesome!  :-D
Thanks!

**Comment by raph-amiard** [comment]
Hey, glad it works for you :) Let me know if you stumble into something else.
